spring:
  datasource:
      url: jdbc:mysql://localhost:3306/rj
      driver-class-name:  com.mysql.cj.jdbc.Driver
      password: 123456
      username: root





mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true

reggie:
  path: D:\imgs\